Repository danielrodajo/media-cloud, pull requests merged in 2020-09, with the labels that each got.

#14 Add page branch
  package-lock.json
  package.json
  src/components/AnimatedCheckmark/AnimatedCheckmark.css
  src/components/AnimatedCheckmark/AnimatedCheckmark.tsx
  src/components/BottomBar/BottomBar.tsx
  src/pages/add/Add.scss
  src/pages/add/Add.tsx
  src/pages/add/PopoverUpload/PopoverUpload.scss
  src/pages/add/PopoverUpload/PopoverUpload.tsx
  src/pages/home/Home.tsx
  src/pages/profile/Profile.tsx
  src/shared/utility.ts
  src/store/actions/ActionTypes.ts
  src/store/actions/FileManager.ts
  src/store/reducers/FileReducer.ts
  src/store/types.ts
Labels: design, feature

#17 Subida de fichero con la camara finalizado.
  src/components/DisplaySelectFile/DisplaySelectFile.css
  src/components/DisplaySelectFile/DisplaySelectFile.tsx
  src/components/PopoverFileBox/PopoverFileBox.tsx
  src/hooks/usePhotoGallery.ts
  src/pages/add/Add.tsx
  src/pages/home/Home.tsx
  src/store/actions/FileManager.ts
Labels: design, feature

#24 Folder navigation branch
  src/components/AnimatedCheckmark/AnimatedCheckmark.css
  src/components/BottomBar/BottomBar.tsx
  src/components/FileBox/FileBox.tsx
  src/components/FolderBox/FolderBox.tsx
  src/components/PopoverFileBox/PopoverFileBox.tsx
  src/pages/add/Add.tsx
  src/pages/add/PopoverUpload/PopoverUpload.tsx
  src/pages/authentication/signout/SignOut.tsx
  src/pages/home/Home.css
  src/pages/home/Home.scss
  src/pages/home/Home.tsx
  src/store/actions/ActionTypes.ts
  src/store/actions/FileManager.ts
  src/store/actions/FolderManager.ts
  src/store/actions/RecoverManager.ts
  src/store/actions/index.ts
  src/store/reducers/FileReducer.ts
  src/store/reducers/FolderReducer.ts
  src/store/types.ts
Labels: design, feature

#27 Splash screen branch
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/drawable/splash2.png
  capacitor.config.json
  src/components/BottomBar/BottomBar.tsx
  src/components/CustomSpinner/CustomSpinner.css
  src/components/CustomSpinner/CustomSpinner.tsx
  src/components/FileBox/FileBox.css
  src/components/FileBox/FileBox.tsx
  src/components/FolderBox/FolderBox.css
  src/components/FolderBox/FolderBox.tsx
  src/components/PopoverFileBox/PopoverFileBox.tsx
  src/default-images/default.jpg
  src/default-images/excel.jpg
  src/pages/add/Add.css
  src/pages/add/Add.tsx
  src/pages/add/PopoverUpload/PopoverUpload.tsx
  src/pages/authentication/signin/SignIn.css
  src/pages/authentication/signin/SignIn.tsx
  src/pages/authentication/signout/SignOut.tsx
  src/pages/home/Home.scss
  src/pages/home/Home.tsx
  src/pages/profile/Profile.tsx
  src/shared/utility.ts
  src/store/actions/FileManager.ts
Labels: bug, design

#30 Agregado pestañas de recientes y todos con su funcionalidad con Redux
  src/components/LoadMyFiles/LoadMyFiles.scss
  src/components/LoadMyFiles/LoadMyFiles.tsx
  src/components/LoadRecents/LoadRecents.scss
  src/components/LoadRecents/LoadRecents.tsx
  src/pages/authentication/signin/SignIn.tsx
  src/pages/home/Home.scss
  src/pages/home/Home.tsx
  src/store/actions/RecoverManager.ts
  src/store/actions/index.ts
  src/store/reducers/FileReducer.ts
Labels: design, feature

#31 Create profile page
  src/components/BottomBar/BottomBar.tsx
  src/images/dani.jpg
  src/images/raul.jpg
  src/images/unnamed.jpg
  src/pages/profile/Profile.css
  src/pages/profile/Profile.tsx
  src/pages/profile/aboutus/AboutUs.css
  src/pages/profile/aboutus/AboutUs.tsx
  src/pages/profile/theme/Theme.tsx
  src/theme/variables.css
Labels: design, enhancement
