Repository danielrodajo/media-cloud, pull requests merged in 2020-10, with the labels that each got.

#34 Modify subpages
  src/components/BottomBar/BottomBar.tsx
  src/components/ToolBar/Toolbar.tsx
  src/pages/authentication/signout/SignOut.css
  src/pages/authentication/signout/SignOut.tsx
  src/pages/profile/Profile.css
  src/pages/profile/Profile.tsx
  src/pages/profile/aboutus/AboutUs.scss
  src/pages/profile/aboutus/AboutUs.tsx
  src/pages/profile/settings/Settings.scss
  src/pages/profile/settings/Settings.tsx
  src/pages/profile/theme/Theme.tsx
  src/theme/variables.css
Labels: design, feature

#37 Graphql implements branch
  .graphqlconfig.yml
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/API.ts
  src/App.tsx
  src/components/BottomBar/BottomBar.tsx
  src/components/BottomBarButtom/BottomBarButton.tsx
  src/components/ToolBar/Toolbar.tsx
  src/components/ToolBarSearch/ToolBarSearch.scss
  src/components/ToolBarSearch/ToolBarSearch.tsx
  src/components/UserSearch/UserSearch.scss
  src/components/UserSearch/UserSearch.tsx
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/pages/authentication/signin/SignIn.tsx
  src/pages/authentication/signup/SignUp.tsx
  src/pages/search/Search.scss
  src/pages/search/Search.tsx
  src/store/actions/AuthManager.ts
  src/testing/Users.json
  src/triggers/cognito-to-dynamodb.js
Labels: design, enhancement, feature, research

#39 Implementado DarkMode. Se persiste en Cognito
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/API.ts
  src/App.tsx
  src/components/BottomBar/BottomBar.tsx
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/pages/authentication/Authentication.tsx
  src/pages/profile/Profile.css
  src/pages/profile/Profile.tsx
  src/pages/profile/settings/Settings.tsx
  src/pages/search/Search.tsx
  src/store/actions/ActionTypes.ts
  src/store/actions/AuthManager.ts
  src/store/actions/index.ts
  src/store/reducers/AuthReducer.ts
  src/triggers/cognito-to-dynamodb.js
Labels: design

#41 Notifications branch
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/API.ts
  src/components/BottomBar/BottomBar.tsx
  src/components/ModalNotifications/ModalNotifications.scss
  src/components/ModalNotifications/ModalNotifications.tsx
  src/components/ModalNotifications/Notification/Notification.scss
  src/components/ModalNotifications/Notification/Notification.tsx
  src/components/ToolBar/Toolbar.scss
  src/components/ToolBar/Toolbar.tsx
  src/components/UserSearch/UserSearch.tsx
  src/default-images/default-avatar.png
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/pages/authentication/signout/SignOut.tsx
  src/pages/friends/Friends.scss
  src/pages/friends/Friends.tsx
  src/pages/profile/Profile.tsx
  src/pages/search/Search.scss
  src/pages/search/Search.tsx
  src/store/actions/ActionTypes.ts
  src/store/actions/NotificationManager.ts
  src/store/actions/index.ts
  src/store/reducers/NotificationReducer.ts
  src/store/store.ts
  src/store/types.ts
Labels: design, enhancement, feature

#43 Friends branch
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/API.ts
  src/App.tsx
  src/components/BottomBar/BottomBar.tsx
  src/components/Friend/Friend.tsx
  src/components/ModalNotifications/ModalNotifications.tsx
  src/components/ModalNotifications/Notification/Notification.tsx
  src/components/ToolBar/Toolbar.tsx
  src/components/UserSearch/UserSearch.tsx
  src/containers/add/Add.scss
  src/containers/add/Add.tsx
  src/containers/add/PopoverUpload/PopoverUpload.scss
  src/containers/add/PopoverUpload/PopoverUpload.tsx
  src/containers/authentication/Authentication.tsx
  src/containers/authentication/forgotpassword/ForgotPassword.css
  src/containers/authentication/forgotpassword/ForgotPassword.tsx
  src/containers/authentication/forgotpasswordsubmit/ForgotPasswordSubmit.css
  src/containers/authentication/forgotpasswordsubmit/ForgotPasswordSubmit.tsx
  src/containers/authentication/signin/SignIn.scss
  src/containers/authentication/signin/SignIn.tsx
  src/containers/authentication/signout/SignOut.css
  src/containers/authentication/signout/SignOut.tsx
  src/containers/authentication/signup/SignUp.css
  src/containers/authentication/signup/SignUp.tsx
  src/containers/authentication/verify/Verify.css
  src/containers/authentication/verify/Verify.tsx
  src/containers/friends/Friends.scss
  src/containers/friends/Friends.tsx
  src/containers/home/Home.scss
  src/containers/home/Home.tsx
  src/containers/home/LoadMyFiles/LoadMyFiles.scss
  src/containers/home/LoadMyFiles/LoadMyFiles.tsx
  src/containers/home/LoadRecents/LoadRecents.scss
  src/containers/home/LoadRecents/LoadRecents.tsx
  src/containers/profile/Profile.css
  src/containers/profile/Profile.tsx
  src/containers/profile/aboutus/AboutUs.scss
  src/containers/profile/aboutus/AboutUs.tsx
  src/containers/profile/settings/Settings.scss
  src/containers/profile/settings/Settings.tsx
  src/containers/search/Search.scss
  src/containers/search/Search.tsx
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/store/actions/ActionTypes.ts
  src/store/actions/FileManager.ts
  src/store/actions/FriendsManager.ts
  src/store/actions/index.ts
  src/store/reducers/AuthReducer.ts
  src/store/reducers/FriendsReducer.ts
Labels: design, feature

#51 Implementado busqueda de ficheros con filtro de nombre
  src/components/ToolBarSearch/ToolBarSearch.tsx
  src/components/UserSearch/UserSearch.tsx
  src/containers/friends/Friends.scss
  src/containers/friends/Friends.tsx
  src/containers/search/Search.tsx
  src/store/actions/ActionTypes.ts
  src/store/actions/RecoverManager.ts
  src/store/actions/index.ts
  src/store/reducers/FileReducer.ts
  src/store/types.ts
Labels: design, feature

#53 More notifications branch
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/API.ts
  src/components/FileBox/FileBox.scss
  src/components/FileBox/FileBox.tsx
  src/components/FolderBox/FolderBox.css
  src/components/ModalNotifications/FriendPetition/FriendPetition.scss
  src/components/ModalNotifications/FriendPetition/FriendPetition.tsx
  src/components/ModalNotifications/ModalNotifications.tsx
  src/components/ModalNotifications/Notification/Notification.scss
  src/components/ModalNotifications/Notification/Notification.tsx
  src/components/ModalShareFriends/ModalShareFriends.tsx
  src/components/ModalSharedFilesFromFriend/ModalSharedFilesFromFriend.scss
  src/components/ModalSharedFilesFromFriend/ModalSharedFilesFromFriend.tsx
  src/containers/friends/Friends.tsx
  src/containers/home/LoadMyFiles/LoadMyFiles.tsx
  src/containers/home/LoadRecents/LoadRecents.tsx
  src/containers/search/Search.tsx
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/shared/utility.ts
  src/store/actions/NotificationManager.ts
Labels: design, feature

#55 Error toasts
  src/containers/authentication/forgotpassword/ForgotPassword.tsx
  src/containers/authentication/forgotpasswordsubmit/ForgotPasswordSubmit.tsx
  src/containers/authentication/signin/SignIn.tsx
  src/containers/authentication/signup/SignUp.scss
  src/containers/authentication/signup/SignUp.tsx
  src/containers/authentication/verify/Verify.tsx
  src/store/actions/AuthManager.ts
Labels: design, enhancement

#57 Solve bugs branch
  amplify/backend/api/mediacloudGraphQL/schema.graphql
  src/App.tsx
  src/components/BottomBar/BottomBar.tsx
  src/components/CustomLoading/CustomLoading.scss
  src/components/CustomLoading/CustomLoading.tsx
  src/components/DisplayImage/DisplayImage.scss
  src/components/DisplayImage/DisplayImage.tsx
  src/components/FileBox/FileBox.scss
  src/components/FileBox/FileBox.tsx
  src/components/FolderBox/FolderBox.tsx
  src/components/Friend/Friend.tsx
  src/components/ModalNotifications/ModalNotifications.tsx
  src/components/ModalShareFriends/ModalShareFriends.tsx
  src/components/ModalSharedFilesFromFriend/ModalSharedFilesFromFriend.tsx
  src/components/PopoverFileBox/PopoverFileBox.scss
  src/components/PopoverFileBox/PopoverFileBox.tsx
  src/components/PopoverShareFileBox/PopoverShareFileBox.tsx
  src/components/ShareFileBox/ShareFileBox.tsx
  src/containers/add/Add.tsx
  src/containers/authentication/signup/SignUp.tsx
  src/containers/friends/Friends.tsx
  src/containers/home/LoadMyFiles/LoadMyFiles.tsx
  src/containers/home/LoadRecents/LoadRecents.tsx
  src/containers/home/LoadShareFilesWithMe/LoadShareFilesWithMe.tsx
  src/containers/search/Search.tsx
  src/default-images/fail-downloading-img.jpg
  src/graphql/schema.json
  src/hooks/useIsMountedRef.ts
  src/shared/utility.ts
  src/store/actions/AuthManager.ts
  src/store/actions/FriendManager.ts
  src/store/actions/RecoverManager.ts
  src/store/actions/index.ts
  src/store/reducers/FriendReducer.ts
  src/store/types.ts
Labels: bug

#61 Agregado full screen image
  android/app/capacitor.build.gradle
  android/app/src/main/res/xml/config.xml
  package-lock.json
  package.json
  src/components/DisplayImage/DisplayImage.tsx
  src/components/FullScreenImage/FullScreenImage.scss
  src/components/FullScreenImage/FullScreenImage.tsx
  src/components/ImageViewer/ReactSimpleImageViewer.tsx
  src/components/ImageViewer/styles.tsx
Labels: design, feature

#64 cambiadas las fotos por defecto de los archivos que no son imagenes
  src/default-images/Alone-rafiki.png
  src/default-images/Alone-rafiki.svg
  src/default-images/Upload-rafiki.png
  src/default-images/Upload-rafiki.svg
  src/default-images/Work time-rafiki.png
  src/default-images/Work time-rafiki.svg
  src/default-images/default-file.png
  src/default-images/default.png
  src/default-images/icons/avi.png
  src/default-images/icons/cad.png
  src/default-images/icons/css.png
  src/default-images/icons/dat.png
  src/default-images/icons/dll.png
  src/default-images/icons/dmg.png
  src/default-images/icons/doc.png
  src/default-images/icons/html.png
  src/default-images/icons/iso.png
  src/default-images/icons/js.png
  src/default-images/icons/mov.png
  src/default-images/icons/mp3.png
  src/default-images/icons/pdf.png
  src/default-images/icons/php.png
  src/default-images/icons/ppt.png
  src/default-images/icons/ps.png
  src/default-images/icons/psd.png
  src/default-images/icons/sql.png
  src/default-images/icons/svg.png
  src/default-images/icons/txt.png
  src/default-images/icons/wmv.png
  src/default-images/icons/xls.png
  src/default-images/icons/xml.png
  src/default-images/icons/zip.png
  src/default-images/pdf.jpg
  src/default-images/pdf.png
  src/default-images/word.jpg
  src/default-images/word.png
  src/shared/utility.ts
Labels: design
